### ISSUE TITLE
Making it much easier and fully automated to install and run VerdictDB

### ISSUE THREAD

**Issue by barzan** [mozafari/verdictdb#115]
- No one should have to compile to be able to use.
- The default options should work just fine.
- For users who just want to install and quickly get a feel for VerdictDB, they shouldn't have to go and spend a lot of time installing Impala or Spark or other hard-to-install engines. Perhaps a docker container or EC2 image or set of command lines or scripts should be used for this purpose

**Comment by devender-yadav** [comment]
+1 for docker image

**Comment by pyongjoo** [comment]
I will close this issue in a few days since now we support (1) the maven central repository and (2) the Python packge index (pypi). In case of Python, the installation is now just a single-line command: https://verdictdb.org/download/
