### ISSUE TITLE
Update online documentation

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#151]
The current documentation is out-dated and requires an update.
I think we need to at least update the online documentation so that:
1. it says we use 'verdict-shell' instead of 'veeline' (or rename verdict-shell to veeline)
2. it has up-to-date examples of how to run queries via VerdictDB using JDBC.

**Comment by pyongjoo** [comment]
Let me close this issue in favor of https://github.com/mozafari/verdictdb/issues/185
