### ISSUE TITLE
Debug indeterministic fails in unit tests

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#172]
I think we need to catch those unit test fails that occur occasionally. Please refer to this insight [page](https://circleci.com/build-insights/gh/mozafari/verdictdb/master). 

I have seen those errors several times from 'Coordinators' and now it looks like we really need to diagnose the root cause of these problems + add more unit tests to prevent them afterwards.

**Comment by pyongjoo** [comment]
I found the error in the coordinator. It was simply that column list is not retrieved from Redshift when search_path is not set. I have added a line, for which I will create a pull request including other fixes.

**Comment by dongyoungy** [comment]
I guess we can close this for now.
