### ISSUE TITLE
Groupby names; Impala show partitions

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#179]
These are currently issues I see. These are fairly minor bugs that can be easily fixed.

1. There are still failed test cases from the groupby name changes.
2. "show partitions" command of Impala throws an exception when there is no partitions. I think we can just catch the exception and returns an empty list inside our JdbcConnection class.

This is related to https://github.com/mozafari/verdictdb/pull/178

**Comment by Beastjoe** [comment]
I think for impala partition, it has already been implemented.
```java
    List<String> partition = new ArrayList<>();
    DbmsQueryResult queryResult;
    if (syntax instanceof ImpalaSyntax) {
      try {
        queryResult = executeQuery(syntax.getPartitionCommand(schema, table));
        for (int i = 0; i < queryResult.getColumnCount(); i++) {
          String columnName = queryResult.getColumnName(i);
          if (columnName.equals("#rows")) {
            break;
          } else partition.add(columnName);
        }
        return partition;
      } catch (Exception e) {
        return partition;
      }
    }
```
