### ISSUE TITLE
User application hangs without explicit System.exit()

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#195]
A user application that uses VerdictDB's jdbc connection hangs even after the program reaches the end of main() function if it does not explicitly call System.exit(). 

I suspect maybe the threads we spawn in VerdictDB are non-daemon and a user application waits for them to terminate. However, I think that a user application having to call System.exit() to end the application is not the expected behavior.

**Comment by pyongjoo** [comment]
This seems to be still an issue; reopen.

**Comment by pyongjoo** [comment]
The fix has been pushed to https://github.com/mozafari/verdictdb/pull/211

However, the fix only works when the query processing is successful. If an error occurs in the middle, the kill logic does not start. I should add more logic (in the finally clause) to always kill the threads.

**Comment by pyongjoo** [comment]
Let me close this issue since I have not observed this recently. However, feel free to open again if there still are remaining problems.
