### ISSUE TITLE
Redshift timestamp error

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#241]
1. Supporting the "Timestamp getTimestamp(int columnIndex, Calendar cal)" function.

2. Prepare the Redshift database with TIMESTAMP WITHOUT TIME ZONE column types for all possible columns.

3. Include all queries for our Redshift tests

**Comment by Beastjoe** [comment]
Hi Yongjoo,

I check the config.yml and right now the impala-redshift flow only test RedshiftTpchSelectQueryCoordinatorTest class. Should I put the tableau queries in another test class, or still in that class?

**Comment by pyongjoo** [comment]
We can just use the existing class.

**Comment by Beastjoe** [comment]
I find some queries in the file contain count distinct. How to deal with that situation?

**Comment by pyongjoo** [comment]
That's a problem. Are there many queries depending on the count-distinct queries? Otherwise, let's comment the count-distinct queries temporarily.

**Comment by Beastjoe** [comment]
Query 4,13,16,21 contains count-distinct.

**Comment by pyongjoo** [comment]
Thanks. Let's comment them out for now. Let me create a separate issue for count-distinct.

**Comment by Beastjoe** [comment]
When running query 20, I meet problem concerning with having.

Query 20:
```
SELECT "supplier"."s_address" AS "s_address",
  "supplier"."s_name" AS "s_name"
FROM "lineitem" "lineitem"
  INNER JOIN "supplier" "supplier" ON ("lineitem"."l_suppkey" = "supplier"."s_suppkey")
  INNER JOIN "nation" "N2" ON ("supplier"."s_nationkey" = "N2"."n_nationkey")
  INNER JOIN "part" "part" ON ("lineitem"."l_partkey" = "part"."p_partkey")
  INNER JOIN (
  SELECT COUNT(1) AS "_tableau_join_flag",
    "partsupp"."ps_partkey" AS "ps_partkey",
    "partsupp"."ps_suppkey" AS "ps_suppkey"
  FROM "lineitem" "lineitem"
    INNER JOIN "supplier" "supplier" ON ("lineitem"."l_suppkey" = "supplier"."s_suppkey")
    INNER JOIN "partsupp" "partsupp" ON (("lineitem"."l_partkey" = "partsupp"."ps_partkey") AND ("lineitem"."l_suppkey" = "partsupp"."ps_suppkey"))
  WHERE ((NOT ("supplier"."s_nationkey" IS NULL)) AND (NOT ("lineitem"."l_partkey" IS NULL)))
  GROUP BY 2,
    3
  HAVING ((CASE WHEN (MIN("partsupp"."ps_availqty") > (0.5 * SUM((CASE WHEN (("lineitem"."l_shipdate" >= (DATE '1994-01-01')) AND ("lineitem"."l_shipdate" < DATEADD(YEAR,1,CAST((DATE '1994-01-01') AS TIMESTAMP WITHOUT TIME ZONE)))) THEN "lineitem"."l_quantity" ELSE NULL END)))) THEN 1 ELSE 0 END) = 1)
) "t0" ON (("lineitem"."l_partkey" = "t0"."ps_partkey") AND ("lineitem"."l_suppkey" = "t0"."ps_suppkey"))
WHERE (("N2"."n_name" = 'CANADA') AND (SUBSTRING("part"."p_name", 1, LENGTH('forest')) = 'forest'))
GROUP BY 1,
  2
```

We used to leaving having to solve at the root of the AsyncAggExecutionNode. However, in the case of query 20, when having clause involve columns that do not appear in the select list, such as ps_availqty, this column cannot be recognized at the root of the AsyncAggExecutionNode. One possible solution is to add this column to the select list of the base AggExecutionNode. Do you have any suggestion?

**Comment by dongyoungy** [comment]
@Beastjoe FYI, we are currently working on the fix for the issue with HAVING in #228

**Comment by Beastjoe** [comment]
I see. Thanks for the reminder。

**Comment by Beastjoe** [comment]
I observe other two errors in redshift query 22 when using verdictdb to run the query. 

The first error is when adding verdicttier column to ProjectionNode during the process of recursively add tier column, if the query originally have group by, it will go wrong because we do not add verdicttier column in group by. In that case, I don't think we should add verdicttier column to ProjectionNode that has group by clause.

The second error is I observe that  DirectRetrievalExecutionNode may cause multiple AsyncAggExecutionNode share one selectQuery. It will cause problem when trying to in the process of replacement. I am trying to see if it can deepcopy the selectQuery.

**Comment by dongyoungy** [comment]
@pyongjoo The symptoms @Beastjoe has mentioned are exactly what I saw previously with Q22.

BTW, for the first problem, shouldn't we be adding `verdictdbtier` to ProjectionNode somehow? It looks like the error is caused by **NOT** having `verdictdbtier` in the group-by of each ProjectionNode?

**Comment by Beastjoe** [comment]
Wait. I just check the query. Can a projection node have group-by clause.
```
SELECT "customer"."c_custkey" AS "c_custkey",
      (CASE WHEN 2 >= 0 THEN SUBSTRING("customer"."c_phone", 1, CAST(FLOOR(2) AS INTEGER)) ELSE NULL END) AS "calculation_5131031153053149"
    FROM "orders" "orders"
      RIGHT JOIN "customer" "customer" ON ("orders"."o_custkey" = "customer"."c_custkey")
      CROSS JOIN (
      SELECT AVG(CAST("t3"."__measure__0" AS DOUBLE PRECISION)) AS "__measure__1"
      FROM (
        SELECT "customer"."c_custkey" AS "c_custkey",
          MAX((CASE WHEN ("customer"."c_acctbal" > 0) THEN "customer"."c_acctbal" ELSE NULL END)) AS "__measure__0"
        FROM "customer" "customer"
        WHERE ((CASE WHEN 2 >= 0 THEN SUBSTRING("customer"."c_phone", 1, CAST(FLOOR(2) AS INTEGER)) ELSE NULL END) IN ('13', '17', '18', '23', '29', '30', '31'))
        GROUP BY 1
      ) "t3"
      HAVING (COUNT(1) > 0)
    ) "t4"
    WHERE (((CASE WHEN 2 >= 0 THEN SUBSTRING("customer"."c_phone", 1, CAST(FLOOR(2) AS INTEGER)) ELSE NULL END) IN ('13', '17', '18', '23', '29', '30', '31')) AND (("customer"."c_acctbal" > "t4"."__measure__1") AND ("orders"."o_orderkey" IS NULL)))
    GROUP BY 1,
      2
```

**Comment by pyongjoo** [comment]
A project node must not include groupby because we are distinguishing a simple projection query and an aggregate query (the latter is handled by AggregateNode). As you know, the groupby can only appear when there exist aggregate functions in the select list.

**Comment by Beastjoe** [comment]
I see. Somehow redshift allows the above queries. I think that's why it causes the first error

**Comment by pyongjoo** [comment]
Hmm. The above query is really unusual, but I think it aims to remove duplicate rows.

I think we have to make an exception to the rule I described above. A projection node may have groupby if it refers to all the elements in the select list.

**Comment by pyongjoo** [comment]
@Beastjoe I believe this issue has been handled by the above pull request (which is already merged to master). If so, please feel free to close this issue. Thanks.

**Comment by Beastjoe** [comment]
I am sorry that I have forget to add getTimestamp(String columnLabel, Calendar cal). I have created a pull request. Please have a check.
