### ISSUE TITLE
Adding the interface for streamsql()

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#257]
@Beastjoe Can you propose what to add and test?

The things I could think of are:
1. Creating a nice print function for a single (individual) result; we can just follow the format offered by typical databases (e.g., MySQL).
2. Adding test cases for streamsql()
    - Retrieving results
    - Ensuring the correctness of individual results
3. Adding a tutorial

**Comment by Beastjoe** [comment]
I think those are enough. 
For creating a nice print function for results, I remember you once said in the future, the print function should additionally add one more column to print the progress or something. (I cannot remember clearly) 
I find this repo https://github.com/htorun/dbtableprinter can be useful for printing function. It is a java utility class to print resultset in database way.

**Comment by Beastjoe** [comment]
I am a bit confused about when should we identify the query type. So far, we identify the query type inside ExecutionContext.streamsql(), which is called by VerdictContext.streamsql(). However, based on your description, I think some function should be created after VerdictStatement.sql() and before VerdictContext.streamsql()

**Comment by pyongjoo** [comment]
When the regular VerdictContext is used, no query type needs to be recognized. It is the user's job to use either sql() or streamsql(). The same select query should be passed to those methods, while the return types are different.

The situation is different when the jdbc interface is used. Since VerdictStatement is now the caller (or the user) of VerdictContext, the VerdictStatement class should recognize the query type and call different methods. Note that the input to the JDBC interface is only a single string query. To distinguish which interface to use (regular or stream), a query can be optionally prepended by "stream".

The only reason that VerdictContext.sql() cannot process "stream select ..." is because its return type is fixed as VerdictSingleResult.
