### ISSUE TITLE
Update an outdated documentation page

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#261]
It has been reported that the below page contains old VerdictDB interface.

https://docs.verdictdb.org/reference/supported_queries/

**Comment by pyongjoo** [comment]
@dongyoungy Can you add a page describing how to specify the loglevel options?

**Comment by dongyoungy** [comment]
I have added 'VerdictDB JDBC Properties' page under 'Getting Started' in the verdictdb-doc repo (not deployed to the website yet). Please take a look and let me know what you think.

**Comment by pyongjoo** [comment]
Thanks! I take a look shortly.

**Comment by pyongjoo** [comment]
@dongyoungy Have you been making changes directly to the verdictdb-doc repo? If so, please move those changes (including the update for adding a variable for a VerdictDB version) to this repository. Currently, it is configured in a way that the content in the docs folder (of this repo) is compiled and deployed to the repository.

**Comment by dongyoungy** [comment]
I created the pull request #262, which includes previous changes I made into verdictdb-doc repo. I guess the verdictdb-doc repo is obsolete now?

**Comment by pyongjoo** [comment]
Thanks. The verdictdb-doc repo is obsolete for making changes. However, it is still serving https://docs.verdictdb.org on its gh-pages branch.

**Comment by pyongjoo** [comment]
@dongyoungy Could you also add a mechanism for compiling and including javadoc html pages in our documentation? I was thinking of adding the process in the `deploy-doc` stage of CircleCI, but other approaches will be good, too.
