### ISSUE TITLE
Partial scramble creation

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#280]
Currently, 100% of the data are used for scrambles. We need to add an option to create partial scrambles, for the case the user would prefer (a) storage cost saving *to* (b) the convergence to an exact answer.

**Comment by Praveen2112** [comment]
Any plans on how to implement them ?

**Comment by pyongjoo** [comment]
We plan to work on this issue after finishing this pull request (related to Presto support): https://github.com/mozafari/verdictdb/pull/282

**Comment by Praveen2112** [comment]
okay. So can we specify the % of data to be used for scrambles ? Like having a maximum storage cost saving ?

**Comment by pyongjoo** [comment]
Yes. If the scramble size is 10% of the original data, the storage saving will be about 90% (which will vary slightly depending on compression scheme, etc.).

**Comment by pyongjoo** [comment]
Update: @dongyoungy has started working on this issue.

**Comment by pyongjoo** [comment]
https://github.com/mozafari/verdictdb/pull/286

**Comment by pyongjoo** [comment]
I close this issue since the related pull request has been merged.
