### ISSUE TITLE
CircleCI: Impala JDBC driver not found with 'build-jdk7' job after pom.xml changed

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdictdb#283]
In the recent PR #282, I have changed pom.xml to include presto jdbc dependency for test.
Since then, it seems to be causing problems with the `build-jdk7` job in CircleCI that unit tests involving Impala fail to find jdbc driver for Impala (relevant CircleCI job [link](https://circleci.com/gh/mozafari/verdictdb/1957)).

I tried to revert back 'install-file' step in CircleCI config and also tried few other changes, but the problem did not get fixed.

@pyongjoo Do you have any ideas on why this might happen?

**Comment by pyongjoo** [comment]
I'm not sure if this is the cause, but [this page](https://github.com/prestodb/presto-jdbc-java6) states that Presto requires JVM8. We could only activate Presto tests for jdk8 cases (with annotations or so).

**Comment by dongyoungy** [comment]
Hmmm... it currently does not have any unit tests for Presto yet... I will first verify that whether just having dependency of presto driver is causing the issue.

**Comment by dongyoungy** [comment]
It is hard to say the exact reason at the moment, but simply having dependency of presto JDBC in pom.xml does seem to cause this issue. I checked this by running CircleCI with/without presto dependency locally.

For now, I think we can:
1) simply drop support for java 7
2) we only include presto in pom.xml for java 8 (do not know how to do this atm - need to figure out)

Option (1) is cleaner, but may cause compatibility issues later.
Option (2) somehow keeps java 7 support, but Maven & CircleCI configs can become messy.

**Comment by pyongjoo** [comment]
Using JUnit Categories could be a clean way to achieving 2: https://github.com/junit-team/junit4/wiki/categories

**Comment by dongyoungy** [comment]
With JUnit Categories, we can exclude all Impala-based unit tests that seem to have problems with Presto for JDK7, but this means we will NOT be testing those unit tests for JDK7 at all. So this is a little different from option (2) as it controls which tests to run, NOT which dependencies to have.

So far, it looks like conditional dependencies using multiple profiles in pom.xml can achieve option (2) ([relevant SO thread](https://stackoverflow.com/questions/24162265/maven-profile-conditional-dependency)), but apparently it is not a good practice.

I will research a little more for a possibly better solution...

**Comment by dongyoungy** [comment]
Closing this as the issue has been resolved with PR #282
