### ISSUE TITLE
Error in run command

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#289]
I run the verdictdb-tutorial, i can run the ./run.sh localhost 3306 tpch1g create, but when I execute the ./run.sh localhost 3306 tpch1g run, i have this error:
![image](https://user-images.githubusercontent.com/15957217/48087166-84bd4100-e1f6-11e8-94bb-c4ec7b2818e8.png)

**Comment by pyongjoo** [comment]
@Beastjoe Could you take a look at this issue?

**Comment by dongyoungy** [comment]
It looks like changing verdictdb version to 0.5.6 in pom.xml seems to fix this issue. I have pushed the change in the verdictdb-tutorial repo.

@solangepaz Please `git pull` on verdictdb-tutorial, rebuild with `mvn clean package` then try again.

**Comment by solangepaz** [comment]
The issue is solved. Thanks
