### ISSUE TITLE
PostgreSQL in PyVerdict

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#325]
Hi,
How can I use it PyVerdict in PostgreSQL database ?

**Comment by pyongjoo** [comment]
Pyverdict does not support Postgres yet. We plan to work on it, but do not have a specific ETA yet.

**Comment by solangepaz** [comment]
Hi, 
I tried to adapt the verdictdb tutorial to use with mysql, but I got this error:

![image](https://user-images.githubusercontent.com/15957217/50743488-8617e380-1210-11e9-8877-2b9cf2183f15.png)

**Comment by solangepaz** [comment]
Ok thank you. But does pyverdict now support postgresql? If yes, it's more simple.

**Comment by pyongjoo** [comment]
Thanks for asking. We are following up with this pull request: https://github.com/mozafari/verdictdb/pull/329
It should be merged into master in a couple of days at most.

**Comment by solangepaz** [comment]
Hi,
In relation to use postgresql with verdictdb in java, i added this line at pom.xml:
![image](https://user-images.githubusercontent.com/15957217/51090618-53bd3780-1776-11e9-8b84-f201d6d15ff5.png)

but i have this error again:
![image](https://user-images.githubusercontent.com/15957217/51090610-443dee80-1776-11e9-8ed9-e0c6639e2cce.png)

**Comment by solangepaz** [comment]
I'm not able to do pull request.

But is it already possible to use pyverdict?

**Comment by XiaoyangShen** [comment]
@solangepaz 
Thank you for your patience. The PyVerdict support for PostgreSQL is ready now; You could pull the newest code and compile the source code (tested on miniconda 3.7):
```bash
cd pyverdict
python setup.py install
```
To use PyVerdict for PostgreSQL, please use the following APIs:
```python
import pyverdict
verdict_conn = pyverdict.postgres(host, port, dbname, user, password)
df = verdict_conn.sql(query) # returns a pandas DataFrame containing results
```
More detailed documentations will be released shortly.

**Comment by solangepaz** [comment]
Thank you. But i have this error, when I try to create a scramble table:

`>>> verdict.sql('create scramble tpch1g.nation_x from tpch1g.nation')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pyverdict/verdictcontext.py", line 226, in sql
    return self.sql_raw_result(query).to_df()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/pyverdict/verdictcontext.py", line 234, in sql_raw_result
    java_resultset = self._context.sql(query)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o2.sql.
: org.verdictdb.exception.VerdictDBDbmsException: Issued the following query: select partattrs from pg_partitioned_table join pg_class on pg_class.relname='nation' and pg_class.oid = pg_partitioned_table.partrelid join information_schema.tables on table_schema='tpch1g' and table_name = 'nation'
ERROR: relation "pg_partitioned_table" does not exist
  Position: 23
        at org.verdictdb.connection.JdbcConnection.executeSingle(JdbcConnection.java:226)
        at org.verdictdb.connection.JdbcConnection.execute(JdbcConnection.java:186)
        at org.verdictdb.connection.JdbcConnection.executeQuery(JdbcConnection.java:232)
        at org.verdictdb.connection.JdbcConnection.getPartitionColumns(JdbcConnection.java:352)
        at org.verdictdb.connection.ConcurrentJdbcConnection.getPartitionColumns(ConcurrentJdbcConnection.java:121)
        at org.verdictdb.connection.CachedDbmsConnection.getPartitionColumns(CachedDbmsConnection.java:163)
        at org.verdictdb.coordinator.ExecutionContext.sql(ExecutionContext.java:181)
        at org.verdictdb.VerdictContext.sql(VerdictContext.java:388)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
`

And it is my databases:
![image](https://user-images.githubusercontent.com/15957217/51426264-e3803d00-1bdf-11e9-989a-0d776e813459.png)

And my database schemas:
![image](https://user-images.githubusercontent.com/15957217/51426261-d19e9a00-1bdf-11e9-8eab-8835cf87d49c.png)

**Comment by solangepaz** [comment]
@XiaoyangShen Why does this happen?

**Comment by XiaoyangShen** [comment]
@solangepaz 
I wasn't able to reproduce your error. Here's what I did:

Pull a PostgreSQL docker for testing:
```bash
docker run --rm -d --name verdictdb-postgres -p 127.0.0.1:5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD="" postgres:10
psql -h localhost -p 5432 -U postgres
```

Import the data (suppose you have already downloaded the tpch1g dataset):
```sql
CREATE SCHEMA tpch1g;
SET search_path to tpch1g;
-- nation
CREATE TABLE IF NOT EXISTS "nation" (
  "n_nationkey"  INT,
  "n_name"       CHAR(25),
  "n_regionkey"  INT,
  "n_comment"    VARCHAR(152),
  "n_dummy"      VARCHAR(10),
  PRIMARY KEY ("n_nationkey"));

-- region
CREATE TABLE IF NOT EXISTS "region" (
  "r_regionkey"  INT,
  "r_name"       CHAR(25),
  "r_comment"    VARCHAR(152),
  "r_dummy"      VARCHAR(10),
  PRIMARY KEY ("r_regionkey"));

-- supplier
CREATE TABLE IF NOT EXISTS "supplier" (
  "s_suppkey"     INT,
  "s_name"        CHAR(25),
  "s_address"     VARCHAR(40),
  "s_nationkey"   INT,
  "s_phone"       CHAR(15),
  "s_acctbal"     DECIMAL(15,2),
  "s_comment"     VARCHAR(101),
  "s_dummy"       VARCHAR(10),
  PRIMARY KEY ("s_suppkey"));

-- customer
CREATE TABLE IF NOT EXISTS "customer" (
  "c_custkey"     INT,
  "c_name"        VARCHAR(25),
  "c_address"     VARCHAR(40),
  "c_nationkey"   INT,
  "c_phone"       CHAR(15),
  "c_acctbal"     DECIMAL(15,2),
  "c_mktsegment"  CHAR(10),
  "c_comment"     VARCHAR(117),
  "c_dummy"       VARCHAR(10),
  PRIMARY KEY ("c_custkey"));

-- part
CREATE TABLE IF NOT EXISTS "part" (
  "p_partkey"     INT,
  "p_name"        VARCHAR(55),
  "p_mfgr"        CHAR(25),
  "p_brand"       CHAR(10),
  "p_type"        VARCHAR(25),
  "p_size"        INT,
  "p_container"   CHAR(10),
  "p_retailprice" DECIMAL(15,2) ,
  "p_comment"     VARCHAR(23) ,
  "p_dummy"       VARCHAR(10),
  PRIMARY KEY ("p_partkey"));

-- partsupp
CREATE TABLE IF NOT EXISTS "partsupp" (
  "ps_partkey"     INT,
  "ps_suppkey"     INT,
  "ps_availqty"    INT,
  "ps_supplycost"  DECIMAL(15,2),
  "ps_comment"     VARCHAR(199),
  "ps_dummy"       VARCHAR(10)
  );

-- orders
CREATE TABLE IF NOT EXISTS "orders" (
  "o_orderkey"       INT,
  "o_custkey"        INT,
  "o_orderstatus"    CHAR(1),
  "o_totalprice"     DECIMAL(15,2),
  "o_orderdate"      DATE,
  "o_orderpriority"  CHAR(15),
  "o_clerk"          CHAR(15),
  "o_shippriority"   INT,
  "o_comment"        VARCHAR(79),
  "o_dummy"          VARCHAR(10),
  PRIMARY KEY ("o_orderkey"));

-- lineitem
CREATE TABLE IF NOT EXISTS "lineitem"(
  "l_orderkey"          INT,
  "l_partkey"           INT,
  "l_suppkey"           INT,
  "l_linenumber"        INT,
  "l_quantity"          DECIMAL(15,2),
  "l_extendedprice"     DECIMAL(15,2),
  "l_discount"          DECIMAL(15,2),
  "l_tax"               DECIMAL(15,2),
  "l_returnflag"        CHAR(1),
  "l_linestatus"        CHAR(1),
  "l_shipdate"          DATE,
  "l_commitdate"        DATE,
  "l_receiptdate"       DATE,
  "l_shipinstruct"      CHAR(25),
  "l_shipmode"          CHAR(10),
  "l_comment"           VARCHAR(44),
  "l_dummy"             VARCHAR(10));

  \copy "region"     from '{root_dir}/tpch1g/region/region.tbl'        DELIMITER '|' CSV;
  \copy "nation"     from '{root_dir}/tpch1g/nation/nation.tbl'        DELIMITER '|' CSV;
  \copy "customer"   from '{root_dir}/tpch1g/customer/customer.tbl'    DELIMITER '|' CSV;
  \copy "supplier"   from '{root_dir}/tpch1g/supplier/supplier.tbl'    DELIMITER '|' CSV;
  \copy "part"       from '{root_dir}/tpch1g/part/part.tbl'            DELIMITER '|' CSV;
  \copy "partsupp"   from '{root_dir}/tpch1g/partsupp/partsupp.tbl'    DELIMITER '|' CSV;
  \copy "orders"     from '{root_dir}/tpch1g/orders/orders.tbl'        DELIMITER '|' CSV;
  \copy "lineitem"   from '{root_dir}/tpch1g/lineitem/lineitem.tbl'    DELIMITER '|' CSV;
```

Install `pyverdict` from PyPI:
```bash
pip install pyverdict
python
```

Perform the queries:
```python
import pyverdict
host = 'localhost'
port = 5432
user = 'postgres'
dbname = 'postgres'
password = ''
verdict_conn = pyverdict.postgres(host, port, dbname, user, password)
verdict_conn.sql('create scramble tpch1g.nation_x from tpch1g.nation')
```
