### ISSUE TITLE
Create Stratified Sampling

### ISSUE THREAD

**Issue by qingzma** [mozafari/verdictdb#342]
Hi, 

I am wondering if there exist any SQL examples to generate stratified samples.
Currently, `METHOD` could only be `(uniform | hash)`

The paper claims the stratified samples are generated in a tricky way using two-pass approach, but could you please provide more details about how to generate the stratified sample?

Thanks,

**Comment by barzan** [comment]
I don't think the stratified samples are in the open-source version. But there's a plan on adding it to the open source version too, hopefully in a week or two.

**Comment by qingzma** [comment]
Thanks for the info.
