### ISSUE TITLE
Dual table names in tutorial

### ISSUE THREAD

**Issue by Chen-Huanyi** [mozafari/verdictdb#346]
In section
[Apache Spark. Create table and load data](https://docs.verdictdb.org/tutorial/tpch/#create-table-and-load-data)
The SQLs are not correct, the last line of each query should be as:

 LOCATION '/tmp/tpch1g/nation/**~~nation~~**';

**Comment by pyongjoo** [comment]
@Chen-Huanyi Thanks for telling us the problem.

@dongyoungy Can you assign this someone to take a look? Thanks.

**Comment by dongyoungy** [comment]
Will be fixed by PR #347
