### ISSUE TITLE
Create sameple table hashing on year(l_shipdate)?

### ISSUE THREAD

**Issue by Chen-Huanyi** [mozafari/verdictdb#356]
I'm trying to test VerdictDB using TPC-H. However, I was wondering if I can create a sample table hashing on an expression of a column?
For example,
```
CREATE SCRAMBLE tpch1g.lineitem_scramble FROM tpch1g.lineitem HASH ON year(l_shipdate) BLOCKSIZE 100
```

**Comment by dongyoungy** [comment]
Hash scrambling only supports hashing on a column currently.

**Comment by Chen-Huanyi** [comment]
How about multiple columns?

**Comment by dongyoungy** [comment]
It only works on a single column at the moment.

**Comment by Chen-Huanyi** [comment]
Got it! Thanks!
