### ISSUE TITLE
verdictdbblock question

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#360]
Is it normal for the verdictdbblock value to always be 0?

**Comment by pyongjoo** [comment]
It could happen if your dataset contains less than one million tuples.

**Comment by solangepaz** [comment]
OK thank you. Is the data stored in some table with the samples, or does this just happen when the queries are being executed through the DAG?

**Comment by pyongjoo** [comment]
A sample (or equivalently, scramble) table is created when you issue a `CREATE SCRAMBLE ...` query.

The scramble table is materialized as a regular table in your database along with materialized `verdictdbblock`. This means "always 0" is stored in the table (not happen at query time).

**Comment by solangepaz** [comment]
And verdictdbtemp is used for what? When I create a scramble the verdictdbtemp has nothing ...

**Comment by pyongjoo** [comment]
The schema is used for storing temporary tables (and removed when you exit VerdictDB). For simple queries, no temporary tables are created, so what you see is expected.

**Comment by solangepaz** [comment]
Ok, thank you.
