### ISSUE TITLE
What are the verdictdbblock used?

### ISSUE THREAD

**Issue by solangepaz** [mozafari/verdictdb#371]
Is it possible to know what are the verdictdbblock that VerdictDB uses to execute a query?

**Comment by pyongjoo** [comment]
Sure.  The value of `verdictdbblock` is used to process only a subset of a scramble (say, 1% of it).  The subset itself amounts to a random sample of the original table, so we can compute unbiased estimators using it.  

As VerdictDB processes more subsets (associated with different `verdictdbblock` values), the accuracy of unbiased estimators increases in expectation.

**Comment by solangepaz** [comment]
Thanks. And is it possible to know, which verdictdbblock are used while executing a query?

**Comment by pyongjoo** [comment]
Yes, both inside VerdictDB modules and by observing the queries issued to an underlying DB.

In general, they are sequential, i.e., the first query is associated with `verdictdbblock=0`, the second query with `verdictdbblock=0`, and so on.  These queries may be issued in parallel to reduce the processing time (e.g., for Presto).

**Comment by solangepaz** [comment]
Do all blocks run until a convergence is reached?

**Comment by pyongjoo** [comment]
No. At most 10 blocks at a time. As soon as one is processed, the next one runs until convergence. Of course, all blocks *may* run if your query selects only a few tuples (thus, convergence is slow).

**Comment by pyongjoo** [comment]
If that is your sole purpose, I would simply turn on the DEBUG option and see what queries are being issued. 

For Java: https://docs.verdictdb.org/reference/properties/
For pyverdict: use `verdict.set_loglevel('debug')`. https://github.com/mozafari/verdictdb/blob/master/pyverdict/pyverdict/verdictcontext.py#L222

**Comment by solangepaz** [comment]
Another question, my idea was to copy the blocks used to another database and then calculate the results. What happens is that for example in the query `select sum(l_extendedprice) from lineitem` blocks 0,1 and 2 are used and the result through verdictDB is **2.294500756989E11**. 
But if I do this query: `select sum (l_extendedprice) from lineitem_scramble where verdictdbblock = 0 or verdictdbblock = 1 or verdictdbblock = 2;` the result with MySQL (for example) is ** 98360078016.67**.
How can I get the 2.294500756989E11 value through the value 98360078016.67 ?

**Comment by solangepaz** [comment]
Is it possible to do this through cumulative distributions?

**Comment by pyongjoo** [comment]
Let me answer this in 10 mins...

**Comment by pyongjoo** [comment]
So, scaling factors are obtained from the cumul distribution stored in the metadata table.

Ex. cumul = [0.2, 0.5, 1.0] means 20% of data is in block0, 30% of data is in block1, and 50% of data is in block2.

In this case, scaling is performed as follows.
1. "sum(col) from block0" is scaled by **(1/0.2)** to produce an unbiased estimator
2. "sum(col) from block0 and block1" is scaled by **(1/0.5)** to produce an unbiased estimator
3. "sum(col) from block0 and block1 and block2" is scaled by **(1/1)** to produce an unbiased estimator

I believe the actual logic is slightly more sophisticated, but the basics are still the same.

**Comment by solangepaz** [comment]
So if I divide the query result into the block by the scale factor, should I get a value close to the real one?
For example, for the lineitem table I have `"cumulativeDistributions" = [ 0,142857, 0,285,714, 0,428571, 0.571429, 0,714,286, 0,857143, 1]`.
If I run this in VerdictDB `select sum (l_extendedprice) from tpch.lineitem_scramble;` I have this result:  2,2966378476811E11, where blocks 0, 1 and 2 are used.
If I do this query in MySQL `select sum (l_extendedprice) from lineitem_scramble where verdictdbblock = 0;` I have this result:  **32775857642,00**/0,142857= 2,294312329252330E11.
--




2,294312329252330E+11
--

**Comment by pyongjoo** [comment]
Yes to the first question.

For joins, 
1. We first compute the prob dist for each joined blocks, e.g., (block0 from left, block0 from right), (block0 from left, block1 from right), and so on. The prob dist for each joined block is then computed by multiplying two individual prob dist.
2. Then, scale factor = 1 / (cumul prob dist), which is the same as single table cases.

**Comment by solangepaz** [comment]
Thank you. And another question, how does verdictdb know which blocks to use?

**Comment by pyongjoo** [comment]
VerdictDB uses block0, block1, block2, and so on.

As it combines the results from different blocks, VerdictDB performs error estimation, and if the error is small enough (or the entire data has been processed), VerdictDB returns a result.

**Comment by solangepaz** [comment]
How is this error estimation calculated?

**Comment by solangepaz** [comment]
I found this in your code "**the values of the result should be within [(1-valueError)*prevValue, (1+valueError)*prevValue]**", but if I do these calculations I can not get the blocks to use.
For example, for this query (blocks 0, 1 and 2 are used): `select sum(l_extendedprice) from lineitem_scramble;`, if I do these calculations:

1. `select sum(l_extendedprice) from lineitem_scramble where verdictdbblock=0;` **Result:  32808330395.53** [(1-0,02)*0, (1+0,02)*0]=[0,0]. 

2. `select sum(l_extendedprice) from lineitem_scramble where verdictdbblock=1;` [(1-0,02)* 32808330395,53 , (1+0,02)* 32808330395,53

**Comment by solangepaz** [comment]
For example, for a query with group by how do I get the value close to the real? If I multiply by the individual probabilities I do not have that value.

**Comment by pyongjoo** [comment]
For error estimation, VerdictDB checks if processing new blocks of data change our estimates much. If the difference is small, VerdictDB considers that the estimates are accurate.

For scaling the aggregate values for group-by queries, there is no difference.  If you can provide an example, we can have a more concrete discussion.

**Comment by solangepaz** [comment]
For example, in this more "complex" query:
`SELECT
    l_orderkey,
    sum(l_extendedprice * (1 - l_discount)) as revenue,
    o_orderdate,
    o_shippriority
FROM
    customer,
    orders,
    lineitem
WHERE
    c_mktsegment = 'BUILDING'
    AND c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND o_orderdate < date '1995-03-15'
    AND l_shipdate > date '1995-03-15'
GROUP BY
    l_orderkey,
    o_orderdate,
    o_shippriority
ORDER BY
    revenue desc,
    o_orderdate
LIMIT 20;
`
How are calculations done to get a value close to the real?

**Comment by pyongjoo** [comment]
Let's think about how to scale the `revenue` value for `l_orderkey = 1` and `l_orderdate = '1998-01-01'` and `o_shippriority = HIGH`.

Suppose:
1. we have processed 40% of the original data (e.g., sampling ratio is 100%, verdictdbblock ranges from 0 and 99, and we have processed verdictdbblock between 0 and 39).
2. `sum(l_extendedprice * (1 - l_discount))` is $3000 (for the group) after processing the 40% of data

Then, an unbiased estimator for the total sum (for the group) is $3000 / 0.4 = $7500, according to [the Horvitz-Thompson Estimator](https://newonlinecourses.science.psu.edu/stat506/node/16/).

**Comment by solangepaz** [comment]
This is not working for the blocks I have, for example, for the `lineitem_scramble` table **"storedProbDist" = [0.14285714285714285, 0.2857142857142857, 0.42857142857142855, 0.5714285714285714, 0.7142857142857143, 0.8571428571428571, 1.0]**

**Comment by pyongjoo** [comment]
This is an expected result. Since there are only a few tuples that include the same `l_orderkey`, the aggregates based on a small sample (say 1%) cannot produce accurate-enough results (as you have observed). In this situation, VerdictDB chooses to process almost all data to guarantee high accuracy.
