### ISSUE TITLE
Estimated Error Details

### ISSUE THREAD

**Issue by DiegoPennino** [mozafari/verdictdb#391]
I'm a PhD Student, I am performing an experimentation for a paper using verdictdb. I would like to provide also error bounds/estimation for the obtained results. I read in the paper that the user can require it to VerdictDB, but I can not find a way to do it using the verdictdb 0.5.8 java version API. Is this my fault or the API does not support it yet? 
From issue #99 I understand that this should be possible.
Thanks for your time.

**Comment by pyongjoo** [comment]
We had the feature but disabled it temporarily. We will soon release another version that provides error bounds. We are using the new version internally, but to release it, we should also update our documentation.

**Comment by 01lin** [comment]
> We had the feature but disabled it temporarily. We will soon release another version that provides error bounds. We are using the new version internally, but to release it, we should also update our documentation.

Does the latest version support error estimation function? Thanks
